.TH FAIL2BAN "1"
.SH NAME
fail2ban \- a set of server and client programs to limit brute force authentication attempts.
.SH DESCRIPTION
Fail2Ban consists of a client, server and some configuration files to achieve limiting 
brute force of authenitcation attempts.

The server program is \fBfail2ban-server\fR which is configured from the configuration files. The
fail2ban-server can also be configured using the \fBfail2ban-client\fR. 

For details on the configuration of fail2ban see the jail.conf(5) manual page.

For details on the configuration of fail2ban-server see the fail2ban-server(1) manual page.

For details on the configuration of fail2ban-client see the fail2ban-client(1) manual page.

For testing regular expressions assocated with filter using the fail2ban-regex program may be of
use and its manual page is fail2ban-regex(1).

.SH FILES
\fI/etc/fail2ban/*\fR
.SH AUTHOR
Manual page written by Daniel Black
.SH "REPORTING BUGS"
Report bugs to https://github.com/fail2ban/fail2ban/issues
.SH COPYRIGHT
Copyright \(co 2013
.br
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).
.SH "SEE ALSO"
.br 
fail2ban-server(1)
fail2ban-client(1)
jail.conf(5)
fail2ban-regex(1)
