#!/usr/bin/python
# This file is part of Fail2Ban.
#
# Fail2Ban is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fail2Ban is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fail2Ban; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


# Iptable wrapper, call the right iptables depending of the ip proposed
# Author: Paul J Aka "Thanat0s"

import sys, re, subprocess

# Try to avoid any shell injections
def noinject(str):
	for banned_chr in "`&;|":
		if banned_chr in str: 
			print "I don't like some chars in your iptables syntax"
			sys.exit(2)                  
	return True

# Main procedure
def main(argv):
 regv4 = re.compile('([0-9]{1,3}\.){3}[0-9]{1,3}')
 if regv4.search(argv):   
    # we are facing to a ipv4
    ret = subprocess.call(["iptables", argv])
    sys.exit(ret)                  
 else:
    # if not, maybe it's a ipv6
    regv6 = re.compile('::[A-Fa-f0-9]{1,4}|(:[A-Fa-f0-9]{1,4}){2,}')
    if regv6.search(argv):
       ret6 = subprocess.call(["ip6tables", argv])
       sys.exit(ret6)                  
    else:
       # if it's not a ipv6 either, we call both iptables
       ret = subprocess.call(["iptables", argv])
       ret6 = subprocess.call(["ip6tables", argv])
       # return worst error code  
       if ret > ret6:
	  sys.exit(ret)
       else:
          sys.exit(ret6)
	
# Main call, pass all variables
if __name__ == "__main__":
	pline = " ".join(sys.argv[1:])
	if noinject(pline):
		main(pline)
