# Fail2Ban configuration file
#
# Author: Konstantin Shalygin
#
# Policy Based Routing rules
#
# Provides the same features, like 'route' action, and fixes the main issue of
# this hardening blocking: block per ip + service port + service protocol.
# Actually you can add more options and do more granular blocking, see `ip rule
# add help`

[Definition]
actionstart = ip route add unreachable 0.0.0.0/0 table <tableid>
actionstop = ip route delete 0.0.0.0/0 table <tableid>
actionban = ip rule add to <ip> ipproto <protocol> sport <port> lookup <tableid>
actionunban = ip rule delete to <ip> ipproto <protocol> sport <port> lookup <tableid>

[Init]
# Option:  tableid
# Note:    ip route table ID
# Values:  [ NUM | STRING ]
tableid = 666

# Option:  port
# Note:    service port number
# Values:  [ NUM ]
port = 22

# Option:  protocol
# Note:    service protocol
# Values:  [ STRING ]
protocol = tcp
