# For available options, please run "fail2ban-server --help".
#FAIL2BAN_OPTIONS="-x"

# fail2ban runs under both the classic start-stop-daemon and the more
# modern supervise-daemon. Below we default to supervise-daemon, but
# only if $supervisor is unset. If you prefer start-stop-daemon,
# comment out the following line.
: ${supervisor:=supervise-daemon}
